---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: secret-operator
  namespace: default
spec:
  interval: 15m
  url: https://helm.mittwald.de
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: secret-operator
  namespace: default
spec:
  chart:
    spec:
      chart: kubernetes-secret-generator
      version: v3.4.0
      sourceRef:
        kind: HelmRepository
        name: secret-operator
        namespace: default
  interval: 15m
  timeout: 5m
  values:
    secretLength: ${SECRET_LENGTH}
