---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secret-operator
  namespace: default
spec:
  interval: 15m
  path: "app/secret-operator"
  prune: true
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      SECRET_LENGTH: "18"
